# Generated by Django 4.1 on 2022-10-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cantidad_de_personas',
            field=models.IntegerField(),
        ),
    ]
