# Generated by Django 4.1 on 2022-10-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0002_alter_reserva_cantidad_de_personas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cantidad_de_personas',
            field=models.IntegerField(max_length=15),
        ),
    ]
