# Generated by Django 4.1 on 2022-10-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0004_alter_reserva_fecha_de_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_de_reserva',
            field=models.DateField(help_text='  aa/mm/dd '),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(help_text='ingrese su numero de 9 digitos', max_length=9),
        ),
    ]
